# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UR8', '0005_auto_20170430_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar/None/default_avatar.png', upload_to='avatars'),
        ),
    ]
